# Generated by Django 5.1.6 on 2026-06-05 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherCacheLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cache_key', models.CharField(max_length=255)),
                ('hit', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WeatherRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(help_text='City or location name', max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('temperature', models.FloatField(help_text='Temperature in Celsius')),
                ('humidity', models.IntegerField(help_text='Relative humidity percentage')),
                ('rain_probability', models.IntegerField(help_text='Rain probability percentage')),
                ('wind_speed', models.FloatField(blank=True, help_text='Wind speed in km/h', null=True)),
                ('risk_score', models.CharField(choices=[('LOW', 'Low Risk'), ('MEDIUM', 'Medium Risk'), ('HIGH', 'High Risk')], default='LOW', max_length=20)),
                ('ai_summary', models.TextField(blank=True, help_text='AI-generated weather summary', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['location', '-created_at'], name='api_weather_locatio_eea820_idx'), models.Index(fields=['created_at'], name='api_weather_created_24729a_idx')],
            },
        ),
    ]
